[project]
name = "kitchen"
version = "0.0.1"
description = "The kitchen service (an example project following along with Microservice APIs by J. Peralta)."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-smorest>=0.46.1",
    "pyyaml>=6.0.2",
]
